import 'package:equatable/equatable.dart';
import 'package:flutter/material.dart';

import '../../../core/constants/app_colors.dart';

/// Severity classification of a single [VitalReading].
enum VitalStatus { healthy, warning, critical, offline }

/// One point-in-time snapshot of all sensor readings.
///
/// Maps 1-to-1 onto the `/patients/{uid}/readings/{ts}` node in Firebase.
class VitalReading extends Equatable {
  const VitalReading({
    required this.timestamp,
    required this.heartRateBpm,
    required this.spo2Percent,
    required this.temperatureC,
    required this.ecgSample,
  });

  /// When the reading was generated by the ESP32 (server time).
  final DateTime timestamp;

  /// Beats per minute.
  final int heartRateBpm;

  /// Blood-oxygen saturation, 0-100.
  final int spo2Percent;

  /// Body temperature in °C.
  final double temperatureC;

  /// Latest ECG voltage sample (mV-ish, used for the live waveform).
  final double ecgSample;

  /// Convenience aggregate status used to colour-code cards.
  VitalStatus get status {
    if (heartRateBpm <= 0 && spo2Percent <= 0) return VitalStatus.offline;
    final Color c = AppColors.vitalsColor(
      heartRate: heartRateBpm,
      spo2: spo2Percent,
    );
    if (c == AppColors.critical) return VitalStatus.critical;
    if (c == AppColors.warning) return VitalStatus.warning;
    return VitalStatus.healthy;
  }

  VitalReading copyWith({
    DateTime? timestamp,
    int? heartRateBpm,
    int? spo2Percent,
    double? temperatureC,
    double? ecgSample,
  }) {
    return VitalReading(
      timestamp: timestamp ?? this.timestamp,
      heartRateBpm: heartRateBpm ?? this.heartRateBpm,
      spo2Percent: spo2Percent ?? this.spo2Percent,
      temperatureC: temperatureC ?? this.temperatureC,
      ecgSample: ecgSample ?? this.ecgSample,
    );
  }

  // ── JSON ─────────────────────────────────────────────────────────────
  factory VitalReading.fromJson(Map<dynamic, dynamic> json) {
    final dynamic rawTimestamp =
        json['ts'] ?? json['timestamp'] ?? json['timestamp_ms'];
    final dynamic rawHeartRate =
        json['hr'] ?? json['heartRateBpm'] ?? json['heart_rate_bpm'];
    final dynamic rawSpo2 =
        json['spo2'] ?? json['spo2Percent'] ?? json['spo2_pct'];
    final dynamic rawTemperature =
        json['temp'] ?? json['temperatureC'] ?? json['temperature'];
    final dynamic rawEcg = json['ecg'] ?? json['ecgSample'] ?? json['ecg_adc'];

    return VitalReading(
      timestamp: _parseTimestamp(rawTimestamp),
      heartRateBpm: (rawHeartRate as num?)?.toInt() ??
          int.tryParse(rawHeartRate?.toString() ?? '') ??
          0,
      spo2Percent: (rawSpo2 as num?)?.toInt() ??
          int.tryParse(rawSpo2?.toString() ?? '') ??
          0,
      temperatureC: (rawTemperature is num)
          ? rawTemperature.toDouble()
          : (rawTemperature is String)
              ? (rawTemperature.toUpperCase() == 'HOT' ? 38.2 : 36.7)
              : 0.0,
      ecgSample: (rawEcg as num?)?.toDouble() ??
          double.tryParse(rawEcg?.toString() ?? '') ??
          0.0,
    );
  }

  static DateTime _parseTimestamp(dynamic raw) {
    if (raw is DateTime) return raw;
    if (raw is num) {
      final int value = raw.toInt();
      if (value <= 0) return DateTime.fromMillisecondsSinceEpoch(0);
      // ESP32 sends boot-relative millis. Those are not wall-clock epoch
      // values, so map them to the current local time instead of Jan 1.
      if (value < 1000000000000) return DateTime.now();
      return DateTime.fromMillisecondsSinceEpoch(value);
    }
    final String text = raw?.toString() ?? '';
    if (text.isEmpty) return DateTime.now();

    final int? parsedInt = int.tryParse(text);
    if (parsedInt != null) {
      if (parsedInt < 1000000000000) return DateTime.now();
      return DateTime.fromMillisecondsSinceEpoch(parsedInt);
    }

    final DateTime? parsedDate = DateTime.tryParse(text);
    if (parsedDate != null) return parsedDate;

    return DateTime.now();
  }

  Map<String, dynamic> toJson() => <String, dynamic>{
        'ts': timestamp.millisecondsSinceEpoch,
        'hr': heartRateBpm,
        'spo2': spo2Percent,
        'temp': temperatureC,
        'ecg': ecgSample,
      };

  /// Empty placeholder used for "no data" states.
  factory VitalReading.empty() => VitalReading(
        timestamp: DateTime.fromMillisecondsSinceEpoch(0),
        heartRateBpm: 0,
        spo2Percent: 0,
        temperatureC: 0,
        ecgSample: 0,
      );

  @override
  List<Object?> get props =>
      <Object?>[timestamp, heartRateBpm, spo2Percent, temperatureC, ecgSample];
}
