// File generated by `flutterfire configure`.
// This is a TEMPLATE — replace placeholder values with the real ones
// produced by the FlutterFire CLI after you run:
//
//     dart pub global activate flutterfire_cli
//     flutterfire configure \
//         --project=ai-health-monitoring-app \
//         --platforms=android,ios,web,windows,macos,linux \
//         --out=lib/firebase_options.dart
//
// Then paste the generated values below. The constants below match the
// Firebase console (https://console.firebase.google.com/project/ai-health-monitoring-app)
// and the Android `google-services.json` so the project compiles even
// before the official generation completes.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  /// Returns the [FirebaseOptions] for the platform the app is currently
  /// running on. Replaces the static `currentPlatform` getter that
  /// `flutterfire configure` normally generates so we can keep this
  /// hand-maintained template file.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    if (defaultTargetPlatform == TargetPlatform.android) return android;
    if (defaultTargetPlatform == TargetPlatform.iOS) return ios;
    if (defaultTargetPlatform == TargetPlatform.macOS) return macos;
    if (defaultTargetPlatform == TargetPlatform.windows) return windows;
    if (defaultTargetPlatform == TargetPlatform.linux) return linux;
    return web;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbYqyeAbpGdY4QEG-njfBJ8AvEI1DsZ5Q',
    appId: '1:762777377782:android:a81b908c2c51ef114cc5d7',
    messagingSenderId: '762777377782',
    projectId: 'ai-health-monitoring-app',
    databaseURL:
        'https://ai-health-monitoring-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ai-health-monitoring-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'TODO_REPLACE_AFTER_FLUTTERFIRE_CONFIGURE',
    appId: 'TODO_REPLACE_AFTER_FLUTTERFIRE_CONFIGURE',
    messagingSenderId: '762777377782',
    projectId: 'ai-health-monitoring-app',
    databaseURL:
        'https://ai-health-monitoring-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    iosBundleId: 'com.example.aiPowerdHealthMonitoringApp',
    storageBucket: 'ai-health-monitoring-app.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDp2G3bZtnqNsTNG2uuF5KN5KTWtuSJxA',
    appId: '1:762777377782:web:60cd5fdef575d2a44cc5d7',
    messagingSenderId: '762777377782',
    projectId: 'ai-health-monitoring-app',
    authDomain: 'ai-health-monitoring-app.firebaseapp.com',
    databaseURL:
        'https://ai-health-monitoring-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ai-health-monitoring-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'TODO_REPLACE_AFTER_FLUTTERFIRE_CONFIGURE',
    appId: 'TODO_REPLACE_AFTER_FLUTTERFIRE_CONFIGURE',
    messagingSenderId: '762777377782',
    projectId: 'ai-health-monitoring-app',
    databaseURL:
        'https://ai-health-monitoring-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ai-health-monitoring-app.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'TODO_REPLACE_AFTER_FLUTTERFIRE_CONFIGURE',
    appId: 'TODO_REPLACE_AFTER_FLUTTERFIRE_CONFIGURE',
    messagingSenderId: '762777377782',
    projectId: 'ai-health-monitoring-app',
    databaseURL:
        'https://ai-health-monitoring-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    iosBundleId: 'com.example.aiPowerdHealthMonitoringApp',
    storageBucket: 'ai-health-monitoring-app.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'TODO_REPLACE_AFTER_FLUTTERFIRE_CONFIGURE',
    appId: 'TODO_REPLACE_AFTER_FLUTTERFIRE_CONFIGURE',
    messagingSenderId: '762777377782',
    projectId: 'ai-health-monitoring-app',
    databaseURL:
        'https://ai-health-monitoring-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ai-health-monitoring-app.firebasestorage.app',
  );
}